# Generated by Django 5.0.6 on 2024-05-29 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=5000)),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=2000)),
                ('autor', models.CharField(max_length=500)),
                ('fecha_publicacion', models.DateTimeField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion.articulo')),
            ],
        ),
    ]
