# Generated by Django 5.0.6 on 2024-05-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informacion', '0002_articulo_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
